kind: pipeline
type: docker
name: default

services:
  - name: database
    image: postgres:15-alpine
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_DB: rizurin_app_test

steps:
  # =========================
  # TEST (ALL EVENTS)
  # =========================
  - name: test
    image: node:20-alpine
    environment:
      DB_HOST: database
    commands:
      - sleep 5
      - npm install
      - npx sequelize-cli db:create --env test || true
      - npm test
    when:
      event:
        - push
        - pull_request

  # =========================
  # BUILD DEV (PR / NON MASTER)
  # =========================
  - name: build_dev_image
    image: plugins/docker
    settings:
      registry: 192.168.8.51:5000
      repo: 192.168.8.51:5000/rizurin/dev/rizurin-app-api
      tags:
        - ${DRONE_COMMIT_SHA}
      username:
        from_secret: docker_user
      password:
        from_secret: docker_pass
      insecure: true
    when:
      event:
        - push
        - pull_request
      branch:
        exclude:
          - master

  # =========================
  # PRODUCTION FLOW
  # =========================

  - name: migrate_production_db
    image: node:20-alpine
    environment:
      NODE_ENV: production
    commands:
      - npm install
      - npx sequelize-cli db:create --env production || true
      - npx sequelize-cli db:migrate --env production
    when:
      event:
        - push
      branch:
        - master

  - name: build_prod_image
    image: plugins/docker
    settings:
      registry: 192.168.8.51:5000
      repo: 192.168.8.51:5000/rizurin/prod/rizurin-app-api
      tags:
        - ${DRONE_COMMIT_SHA}
      username:
        from_secret: docker_user
      password:
        from_secret: docker_pass
      insecure: true
    when:
      event:
        - push
      branch:
        - master

  - name: deploy_to_k8s
    image: bitnami/kubectl:latest
    environment:
      KUBECONFIG_CONTENT:
        from_secret: kubeconfig
    commands:
      - mkdir -p ~/.kube
      - echo "$KUBECONFIG_CONTENT" > ~/.kube/config

      # optional apply (kalau ada perubahan manifest)
      - kubectl apply -f k8s/

      # update image pakai commit SHA
      - kubectl set image deployment/rizurin-app-api \
        rizurin-app-api=192.168.8.51:5000/rizurin/prod/rizurin-app-api:${DRONE_COMMIT_SHA} \
        -n rizurin

      - kubectl rollout status deployment/rizurin-app-api -n rizurin
    when:
      event:
        - push
      branch:
        - master